management:
  endpoints:
    web:
      exposure:
# todo
#        include: ["api/person", "hystrix.stream", "health", "info", "metrics", "trace"]
        include: "*"
#        exclude: "*"
#      base-path: "/"

spring:
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    type: org.hsqldb.jdbc.JDBCDataSource
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    database-platform: org.hibernate.dialect.HSQLDialect
    database: HSQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true


